root: ./

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    buy-store-and-stake-pokt/: ./pokt/README.md
    resources/references/supported-blockchains/: ./supported-blockchains.md
    v0/glossary/: ./learn/glossary.md
    v0/protocol/: ./learn/protocol/README.md
    v0/protocol/security/: ./learn/protocol/security.md
    v0/protocol/servicing/: ./learn/protocol/servicing.md
    v0/economics/: ./learn/economics/README.md
    v0/economics/monetary-policy/: ./learn/economics/monetary-policy.md
    v0/economics/monetary-policy/monetary-phases/: ./learn/economics/monetary-policy.md
    v0/economics/monetary-policy/application-burn-rate/: ./learn/economics/monetary-policy.md
    v0/economics/monetary-policy/pokt-inflation/: ./learn/economics/monetary-policy.md
    v0/economics/the-web3-infra-trap/: ./learn/economics/README.md
    v0/economics/decentralizing-infrastructure/: ./learn/vision.md
    v0/economics/pokt-token-economics/: ./learn/economics/token-economics.md
    v0/economics/pokt-token-economics/token-staking/: ./learn/economics/token-economics.md
    v0/economics/pokt-token-economics/app-economics/: ./learn/economics/app-economics.md
    v0/economics/pokt-token-economics/app-economics/stability-adjustment/: ./learn/economics/stability-adjustment.md
    v0/economics/pokt-token-economics/app-economics/participation-rate/: ./learn/economics/participation-rate.md
    v0/economics/pokt-token-economics/app-economics/base-throughput/: ./learn/economics/base-throughput.md
    v0/economics/pokt-token-economics/node-economics/: ./learn/economics/node-economics.md
    v0/economics/pokt-token-economics/node-economics/cost-to-nodes/: ./learn/economics/cost-to-nodes.md
    v0/economics/pokt-token-economics/node-economics/economic-security/: ./learn/economics/economic-security.md
    v1/v1-overview/: ./learn/future/README.md
    v1/consensus/: ./learn/future/consensus.md
    v1/peer-to-peer/: ./learn/future/peer-to-peer.md
    v1/persistence/: ./learn/future/persistence.md
    v1/utility/: ./learn/future/utility.md
    pokt-accounts-and-transactions/: ./integrate/README.md
    pokt-accounts-and-transactions/address-generation-and-validation/: ./integrate/accounts-transactions/account-generation-validation.md
    pokt-accounts-and-transactions/deposit-processing-and-verification/: ./integrate/accounts-transactions/transaction-verification.md
    pokt-accounts-and-transactions/transaction-construction-and-offline-signature/: ./integrate/accounts-transactions/transaction-construction.md
    resources/references/pokt-denominations/: ./learn/economics/token-economics.md
    paths/node-runner/zero-to-node/: ./node/tutorials/zero-to-node/README.md
    paths/node-runner/zero-to-node/server-setup/: ./node/tutorials/zero-to-node/server-setup.md
    paths/node-runner/zero-to-node/software-install/: ./node/tutorials/zero-to-node/software-install.md
    paths/node-runner/zero-to-node/pocket-config/: ./node/tutorials/zero-to-node/pocket-config.md
    paths/node-runner/zero-to-node/proxy-config/: ./node/tutorials/zero-to-node/proxy-config.md
    paths/node-runner/zero-to-node/going-live/: ./node/tutorials/zero-to-node/going-live.md
    paths/node-runner/maximize-your-pokt-earnings/: ./node/faq.md
    resources/faq/pricing-and-economics/: ./learn/economics/faq.md
    resources/faq/node-configuration/: ./node/faq.md
    resources/faq/node-troubleshooting/: ./node/faq.md
    resources/faq/wpokt/: ./pokt/wpokt.md
    resources/references/seeds/: ./node/seeds.md
    resources/references/protocol-parameters/: ./learn/protocol-parameters.md
