root: ./

structure:
    readme: README.md
    summary: SUMMARY.md

redirects:
    buy-store-and-stake-pokt.md: ./pokt/README.md
    resources/references/supported-blockchains: ./supported-blockchains.md
    v0/glossary: ./learn/glossary.md
    v0/protocol/README: ./learn/protocol/README.md
    v0/protocol/security: ./learn/protocol/security.md
    v0/protocol/servicing: ./learn/protocol/servicing.md
    v0/economics/README: ./learn/economics/README.md
    v0/economics/monetary-policy: ./learn/economics/monetary-policy.md
    v0/economics/monetary-policy/README: ./v0/economics/monetary-policy.md
    v0/economics/monetary-policy/monetary-phases: ./v0/economics/monetary-policy.md
    v0/economics/monetary-policy/application-burn-rate: ./v0/economics/monetary-policy.md
    v0/economics/monetary-policy/pokt-inflation: ./v0/economics/monetary-policy.md
    v0/economics/the-web3-infra-trap: ./learn/economics/README.md
    v0/economics/decentralizing-infrastructure: ./learn/vision.md
    v0/economics/pokt-token-economics: ./learn/economics/token-economics.md
    v0/economics/pokt-token-economics/token-staking: ./learn/economics/token-economics.md
    v0/economics/pokt-token-economics/app-economics/README: ./learn/economics/app-economics.md
    v0/economics/pokt-token-economics/app-economics/stability-adjustment: ./learn/economics/stability-adjustment.md
    v0/economics/pokt-token-economics/app-economics/participation-rate: ./learn/economics/participation-rate.md
    v0/economics/pokt-token-economics/app-economics/base-throughput: ./learn/economics/base-throughput.md
    v0/economics/pokt-token-economics/node-economics/README: ./learn/economics/node-economics.md
    v0/economics/pokt-token-economics/node-economics/cost-to-nodes: ./learn/economics/cost-to-nodes.md
    v0/economics/pokt-token-economics/node-economics/economic-security: ./learn/economics/economic-security.md
    v1/v1-overview: ./learn/future/README.md
    v1/consensus: ./learn/future/consensus.md
    v1/peer-to-peer: ./learn/future/peer-to-peer.md
    v1/persistence: ./learn/future/persistence.md
    v1/utility: ./learn/future/utility.md
    resources/references/pokt-denominations: ./learn/economics/token-economics.md