hugo:
  # fullnameOverride: hugo
  deployments:
    hugo:
      horizontalPodAutoscaler:
        enabled: true
        minReplicas: 2
        maxReplicas: 5
        targetCPUUtilizationPercentage: 70
      persistence:
        volumeClaimTemplates:
          size: 1Gi
          storageClassName: standard-rwo
          volumeMountPath: /data
      initContainers:
        get-repo:
          image:
            repository: pocketfoundation/hugo
            tag: "latest"
          env:
            - name: GIT_URL
              value: "https://github.com/pokt-foundation/docs.git"
            - name: GIT_BRANCH
              value: "deploy-with-argocd"                   
          command:
            - 'sh'
            - '-c'
            - |
              if [ ! -d /data/src ]; then
                echo "Cloning the repo"
                git clone --recursive $GIT_URL /data/src
              fi
              cd /data/src
              git checkout $GIT_BRANCH
              git pull
              hugo config --source=/data/src --config=config.toml
          volumeMounts:
            - name: hugo-data
              mountPath: /data

      containers:
        hugo:
          image:
            repository: pocketfoundation/hugo
            tag: "latest"
          workingDir: "/data/src"
          command:
          # - sleep
          # - "1000000"
          args:
            - server
            - --source=/data/src
            - --config=config.toml
            - --bind=0.0.0.0
            - --poll=60s
          # resources:
          #   limits:
          #     cpu: 4Gi
          #     memory: 4Gi
          #   requests:
          #     cpu: 1Gi
          #     memory: 2Gi

          # envFrom:
          #   - secretRef:
          #       name: 

          ports:
            - name: http
              port: 1313
              protocol: TCP
              service:
                type: ClusterIP
                annotations:
                  cloud.google.com/neg: '{"ingress": true}'
              ingress:
                annotations:
                  kubernetes.io/ingress.class: "gce"
                  kubernetes.io/ingress.global-static-ip-name: "docs-vip" #* `docs-vip` is created with TF
                  networking.gke.io/managed-certificates: hugo-ssl-cert
                hosts:
                  - host: "docs.portal.pokt.network"
                    paths:
                      - path: /
                        pathType: Prefix
                # tls:
                #   - secretName: pub-tls
                #     hosts:
                #       - "docs.pokt.network"

          livenessProbe:
            tcpSocket:
              port: 1313
  global:
    imagePullPolicy: Always    #* To always get the newest available "latest"
    serviceAccount:
      name: hugo
    securityContext:
      fsGroup: 1001
      runAsUser: 1001
      runAsGroup: 1001

  additionalManifests:
    - kind: ManagedCertificate
      apiVersion: networking.gke.io/v1
      metadata:
        name: hugo-ssl-cert
      spec:
        domains:
          - docs.portal.pokt.network
