nginx:
  image:
    registry: ghcr.io
    repository: pokt-foundation/docs
    tag: sha-4512415

  service:
    type: ClusterIP
    annotations:
      cloud.google.com/neg: '{"ingress": true}'

  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.global-static-ip-name: "docs-vip" #* `docs-vip` is created with TF
      kubernetes.io/ingress.allow-http: "false"
      networking.gke.io/managed-certificates: docs-ssl-cert
    pathType: Prefix
    hostname: docs-network.portal.pokt.network
    path: /

  extraDeploy:
    - kind: ManagedCertificate
      apiVersion: networking.gke.io/v1
      metadata:
        name: docs-ssl-cert
      spec:
        domains:
          - docs-network.portal.pokt.network
